name: deploy-orders

on:
    push:
        branches:
            - main
        paths:
            - 'orders/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Build docker image
              run: cd orders && docker build -t msoffredi/orders .

            - name: Login to docker
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

            - name: Push image to DockerHub
              run: docker push msoffredi/orders

            # - uses: <something about aws or aws-cli with some credentials as secrets>
            # - name: Adding EKS cluster to kubectl config
            #   run: <some commands to achieve the above>

            # - name: Restarting orders deployment
            #   run: kubectl rollout restart deployment orders-depl
