name: deploy-auth

on:
    push:
        branches:
            - main
        paths:
            - 'auth/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build docker image
              run: cd auth && docker build -t msoffredi/auth .
            - name: Login to docker
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - name: Push image to DockerHub
              run: docker push msoffredi/auth
