name: deploy-client

on:
    push:
        branches:
            - main
        paths:
            - 'client/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Build docker image
              run: cd client && docker build -t msoffredi/client .

            - name: Login to docker
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

            - name: Push image to DockerHub
              run: docker push msoffredi/client

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Adding kubernetes cluster as new context
              run: aws eks update-kubeconfig --region us-east-1 --name ticketing

            - name: Restarting client deployment
              run: kubectl rollout restart deployment client-depl
