name: tests-tickets

on:
    pull_request:
        paths:
            - 'tickets/**'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run tickets service tests
              run: cd tickets && npm install && npm run test:ci
