name: tests-orders

on:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run orders service tests
              run: cd orders && npm install && npm run test:ci
